
package com.company;

import java.awt.CardLayout;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;


public class GUI extends javax.swing.JFrame {


    private JSONWeatherParser.weather weather;
    private List<JSONWeatherParser.weather> weatherForecast;
    private CardLayout card;


    public void setweatherForecast(List<JSONWeatherParser.weather> weatherForecast) {
        this.weatherForecast = weatherForecast;
    }
    public void setweather(JSONWeatherParser.weather weather) {
        this.weather = weather;
    }

    public GUI() {
        //Create a new list which contains the cities for the combo box
        List<String> cities = new ArrayList<String>();
        try {
            //Read in the cities CSV file and add contents to the cities list
            BufferedReader bufferedReader = new BufferedReader(new FileReader("Cities.csv"));
            String line;
            while ((line = bufferedReader.readLine()) != null) {
                line = line.replace(",", ", ");
                cities.add(line);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        //Add the contents of the cities list to the combobox
        jComboBoxLocations.setModel(new DefaultComboBoxModel(cities.toArray()));
        this.card = (CardLayout)jPanelStart.getLayout();
    }


    ///////////////////////////////Getters for the labels allows them to be updated \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
    public JLabel getjLabelTemp1(){
        return jLabelTemp1;
    }
    public JLabel getjLabelTemp2(){
        return jLabelTemp2;
    }
    public JLabel getjLabelTemp3(){
        return jLabelTemp3;
    }
    public JLabel getjLabelTemp4(){
        return jLabelTemp4;
    }
    public JLabel getjLabelTemp5(){
        return jLabelTemp5;
    }
    public JLabel getjLabelIcon1(){
        return jLabelIcon1;
    }
    public JLabel getjLabelIcon2(){
        return jLabelIcon2;
    }
    public JLabel getjLabelIcon3(){
        return jLabelIcon3;
    }
    public JLabel getjLabelIcon4(){
        return jLabelIcon4;
    }
    public JLabel getjLabelIcon5(){
        return jLabelIcon5;
    }
    public JLabel getjLabelDate1(){
        return jLabelDate1;
    }
    public JLabel getjLabelDate2(){
        return jLabelDate2;
    }
    public JLabel getjLabelDate3(){
        return jLabelDate3;
    }
    public JLabel getjLabelDate4(){
        return jLabelDate4;
    }
    public JLabel getjLabelDate5(){
        return jLabelDate5;
    }
    public JLabel getjLabelDescription1(){
        return jLabelDescription1;
    }
    public JLabel getjLabelDescription2(){
        return jLabelDescription2;
    }
    public JLabel getjLabelDescription3(){
        return jLabelDescription3;
    }
    public JLabel getjLabelDescription4(){
        return jLabelDescription4;
    }
    public JLabel getjLabelDescription5(){
        return jLabelDescription5;
    }
    public JLabel getjLabelStatus() {
        return jLabelStatus;
    }
    public JLabel getjLabelCurrentLocation() {
        return jLabelCurrentLocation;
    }
    public JLabel getjLabelMap(){
        return jLabelMap;
    }
    public JLabel getjLabelLocation() {
        return jLabelLocation;
    }
    public JLabel getjLabelCloudiness() {
        return jLabelCloudiness;
    }
    public JLabel getjLabelHumidity() {
        return jLabelHumidity;
    }
    public JLabel getjLabelIcon() {
        return jLabelIcon;
    }
    public JLabel getjLabelMaximumTemp() {
        return jLabelMaximumTemp;
    }
    public JLabel getjLabelMinimumTemp() {
        return jLabelMinimumTemp;
    }
    public JLabel getjLabelPressure() {
        return jLabelPressure;
    }
    public JLabel getjLabelRain() {
        return jLabelRain;
    }
    public JLabel getjLabelSunriseTime() {
        return jLabelSunriseTime;
    }
    public JLabel getjLabelSunset() {
        return jLabelSunset;
    }
    public JLabel getjLabelTemperature() {
        return jLabelTemperature;
    }
    public JLabel getjLabelWindDirection() {
        return jLabelWindDirection;
    }
    public JLabel getjLabelWindSpeed() {
        return jLabelWindSpeed;
    }


    ///////////////////////////////Code Generated by netbeans \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanelStart = new javax.swing.JPanel();
        jPanelSearch = new javax.swing.JPanel();
        jComboBoxLocations = new javax.swing.JComboBox<>();
        jLabelSelectCity = new javax.swing.JLabel();
        jTextFieldLongitude = new javax.swing.JTextField();
        jTextFieldSearchPostCode = new javax.swing.JTextField();
        jTextFieldSearchCity = new javax.swing.JTextField();
        jTextFieldLatitude = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();
        jButtonCurrentLocation = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jPanelMain = new javax.swing.JPanel();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanelCurrentDay = new javax.swing.JPanel();
        jLabelMaximumTemp = new javax.swing.JLabel();
        jLabelTemperature = new javax.swing.JLabel();
        jLabelLocation = new javax.swing.JLabel();
        jLabelPressure = new javax.swing.JLabel();
        jLabelMap = new javax.swing.JLabel();
        jLabelHumidity = new javax.swing.JLabel();
        jLabelCurrentLocation = new javax.swing.JLabel();
        jLabelWindSpeed = new javax.swing.JLabel();
        jLabelWindDirection = new javax.swing.JLabel();
        jLabelCloudiness = new javax.swing.JLabel();
        jLabelRain = new javax.swing.JLabel();
        jLabelSunriseTime = new javax.swing.JLabel();
        jLabelSunset = new javax.swing.JLabel();
        jLabelIcon = new javax.swing.JLabel();
        jLabelMinimumTemp = new javax.swing.JLabel();
        jLabelStatus = new javax.swing.JLabel();
        jRadioButtonFahrenheit2 = new javax.swing.JRadioButton();
        jRadioButtonCelsius2 = new javax.swing.JRadioButton();
        jRadioButtonKelvin2 = new javax.swing.JRadioButton();
        jLabelSelectTemp2 = new javax.swing.JLabel();
        jButtonNewSearch3 = new javax.swing.JButton();
        jPanel5Day = new javax.swing.JPanel();
        jLabelIcon1 = new javax.swing.JLabel();
        jLabelDate1 = new javax.swing.JLabel();
        jLabelDescription1 = new javax.swing.JLabel();
        jLabelTemp1 = new javax.swing.JLabel();
        jLabelDescription2 = new javax.swing.JLabel();
        jLabelTemp2 = new javax.swing.JLabel();
        jLabelIcon2 = new javax.swing.JLabel();
        jLabelDate2 = new javax.swing.JLabel();
        jLabelDescription3 = new javax.swing.JLabel();
        jLabelTemp3 = new javax.swing.JLabel();
        jLabelIcon3 = new javax.swing.JLabel();
        jLabelDate3 = new javax.swing.JLabel();
        jLabelDescription4 = new javax.swing.JLabel();
        jLabelTemp4 = new javax.swing.JLabel();
        jLabelIcon4 = new javax.swing.JLabel();
        jLabelDate4 = new javax.swing.JLabel();
        jLabelIcon5 = new javax.swing.JLabel();
        jLabelDate5 = new javax.swing.JLabel();
        jLabelDescription5 = new javax.swing.JLabel();
        jLabelTemp5 = new javax.swing.JLabel();
        jLabelSelectTemp1 = new javax.swing.JLabel();
        jButtonNewSearch2 = new javax.swing.JButton();
        jRadioButtonKelvin1 = new javax.swing.JRadioButton();
        jRadioButtonCelsius1 = new javax.swing.JRadioButton();
        jRadioButtonFahrenheit1 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 73, 95));
        setResizable(false);
        setSize(new java.awt.Dimension(900, 360));

        jPanelStart.setBackground(new java.awt.Color(51, 73, 95));
        jPanelStart.setPreferredSize(new java.awt.Dimension(900, 360));
        jPanelStart.setSize(new java.awt.Dimension(900, 360));
        jPanelStart.setLayout(new java.awt.CardLayout());

        jPanelSearch.setBackground(new java.awt.Color(51, 73, 95));
        jPanelSearch.setPreferredSize(new java.awt.Dimension(900, 360));
        jPanelSearch.setSize(new java.awt.Dimension(900, 360));

        jComboBoxLocations.addActionListener(this::jComboBoxLocationsActionPerformed);

        jLabelSelectCity.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSelectCity.setText("Select City:");

        jTextFieldLongitude.setText("Longitude");
        jTextFieldLongitude.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldLongitudeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldLongitudeFocusLost(evt);
            }
        });


        jTextFieldSearchPostCode.setText("Search Postcode");
        jTextFieldSearchPostCode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldSearchPostCodeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldSearchPostCodeFocusLost(evt);
            }
        });
        jTextFieldSearchPostCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldSearchPostCodeKeyPressed(evt);
            }
        });

        jTextFieldSearchCity.setText("Search City");
        jTextFieldSearchCity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldSearchCityFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldSearchCityFocusLost(evt);
            }
        });
        jTextFieldSearchCity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldSearchCityKeyPressed(evt);
            }
        });

        jTextFieldLatitude.setText("Latitude");
        jTextFieldLatitude.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldLatitudeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldLatitudeFocusLost(evt);
            }
        });

        jTextFieldLatitude.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldLatitudeKeyPressed(evt);
            }
        });

        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(this::jButtonSearchActionPerformed);

        jButtonCurrentLocation.setText("Current Location");
        jButtonCurrentLocation.addActionListener(this::jButtonCurrentLocationActionPerformed);

        jLabel21.setIcon(new javax.swing.ImageIcon("Icons/weather.gif")); // NOI18N

        javax.swing.GroupLayout jPanelSearchLayout = new javax.swing.GroupLayout(jPanelSearch);
        jPanelSearch.setLayout(jPanelSearchLayout);
        jPanelSearchLayout.setHorizontalGroup(
                jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelSearchLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelSearchLayout.createSequentialGroup()
                                                .addComponent(jTextFieldLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextFieldLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jTextFieldSearchPostCode, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldSearchCity, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonCurrentLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanelSearchLayout.createSequentialGroup()
                                                .addComponent(jLabelSelectCity)
                                                .addGap(18, 18, 18)
                                                .addComponent(jComboBoxLocations, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
                                .addComponent(jLabel21)
                                .addGap(74, 74, 74))
        );
        jPanelSearchLayout.setVerticalGroup(
                jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelSearchLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonCurrentLocation)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldSearchCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldSearchPostCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jTextFieldLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jTextFieldLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelSelectCity)
                                        .addComponent(jComboBoxLocations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanelSearchLayout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 28, Short.MAX_VALUE))
        );

        jPanelStart.add(jPanelSearch, "cardSearch");

        jPanelMain.setBackground(new java.awt.Color(51, 73, 95));
        jPanelMain.setPreferredSize(new java.awt.Dimension(900, 360));
        jPanelMain.setRequestFocusEnabled(false);
        jPanelMain.setSize(new java.awt.Dimension(900, 360));

        jTabbedPane.setBackground(new java.awt.Color(26, 37, 48));

        jPanelCurrentDay.setBackground(new java.awt.Color(51, 73, 95));
        jPanelCurrentDay.setPreferredSize(new java.awt.Dimension(900, 480));
        jPanelCurrentDay.setRequestFocusEnabled(false);
        jPanelCurrentDay.setSize(new java.awt.Dimension(900, 480));

        jLabelMaximumTemp.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMaximumTemp.setText("Maximum Temp:");

        jLabelTemperature.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTemperature.setText("Temperature:");

        jLabelLocation.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabelLocation.setForeground(new java.awt.Color(255, 255, 255));

        jLabelPressure.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPressure.setText("Pressure:");

        jLabelHumidity.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHumidity.setText("Humidity:");

        jLabelCurrentLocation.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCurrentLocation.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabelCurrentLocation.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCurrentLocation.setText("Current Location:");

        jLabelWindSpeed.setForeground(new java.awt.Color(255, 255, 255));
        jLabelWindSpeed.setText("Wind Speed:");

        jLabelWindDirection.setForeground(new java.awt.Color(255, 255, 255));
        jLabelWindDirection.setText("Wind Direction:");

        jLabelCloudiness.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCloudiness.setText("Cloudiness:");

        jLabelRain.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRain.setText("Rain:");

        jLabelSunriseTime.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSunriseTime.setText("Sunrise Time:");

        jLabelSunset.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSunset.setText("Sunset Time:");

        jLabelMinimumTemp.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMinimumTemp.setText("Minimum Temp:");

        jLabelStatus.setForeground(new java.awt.Color(255, 255, 255));
        jLabelStatus.setText("Status:");

        buttonGroup1.add(jRadioButtonFahrenheit2);
        jRadioButtonFahrenheit2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonFahrenheit2.setText("Fahrenheit");
        jRadioButtonFahrenheit2.addActionListener(this::jRadioButtonFahrenheit2ActionPerformed);

        buttonGroup1.add(jRadioButtonCelsius2);
        jRadioButtonCelsius2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonCelsius2.setText("Celsius");
        jRadioButtonCelsius2.addMouseListener(new java.awt.event.MouseAdapter() {

        });
        jRadioButtonCelsius2.addActionListener(this::jRadioButtonCelsius2ActionPerformed);

        buttonGroup1.add(jRadioButtonKelvin2);
        jRadioButtonKelvin2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonKelvin2.setText("Kelvin");
        jRadioButtonKelvin2.addMouseListener(new java.awt.event.MouseAdapter() {

        });
        jRadioButtonKelvin2.addActionListener(this::jRadioButtonKelvin2ActionPerformed);

        jLabelSelectTemp2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSelectTemp2.setText("Select Temperature Unit:");

        jButtonNewSearch3.setText("Search New Location");
        jButtonNewSearch3.addActionListener(this::jButtonNewSearch3ActionPerformed);

        javax.swing.GroupLayout jPanelCurrentDayLayout = new javax.swing.GroupLayout(jPanelCurrentDay);
        jPanelCurrentDay.setLayout(jPanelCurrentDayLayout);
        jPanelCurrentDayLayout.setHorizontalGroup(
                jPanelCurrentDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelCurrentDayLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelCurrentDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCurrentDayLayout.createSequentialGroup()
                                                .addGroup(jPanelCurrentDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCurrentDayLayout.createSequentialGroup()
                                                                .addGroup(jPanelCurrentDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPanelCurrentDayLayout.createSequentialGroup()
                                                                                .addGroup(jPanelCurrentDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                        .addComponent(jLabelStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                        .addComponent(jLabelTemperature, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                        .addComponent(jLabelPressure, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                        .addComponent(jLabelHumidity, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addGroup(jPanelCurrentDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                        .addComponent(jLabelRain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                        .addComponent(jLabelCloudiness, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                        .addComponent(jLabelWindDirection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                        .addComponent(jLabelWindSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                        .addComponent(jLabelLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(jPanelCurrentDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPanelCurrentDayLayout.createSequentialGroup()
                                                                                .addGap(17, 17, 17)
                                                                                .addGroup(jPanelCurrentDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(jPanelCurrentDayLayout.createSequentialGroup()
                                                                                                .addGroup(jPanelCurrentDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                        .addComponent(jLabelSunriseTime, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                                                                                        .addComponent(jLabelSunset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                                                .addGap(143, 143, 143))
                                                                                        .addComponent(jLabelCurrentLocation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                                        .addGroup(jPanelCurrentDayLayout.createSequentialGroup()
                                                                                .addGap(18, 18, 18)
                                                                                .addGroup(jPanelCurrentDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                        .addComponent(jLabelIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addGroup(jPanelCurrentDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addComponent(jLabelMinimumTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(jLabelMaximumTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                .addGap(7, 7, 7))))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCurrentDayLayout.createSequentialGroup()
                                                                .addComponent(jLabelMap, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, Short.MAX_VALUE)))
                                                .addGap(109, 109, 109))
                                        .addGroup(jPanelCurrentDayLayout.createSequentialGroup()
                                                .addComponent(jButtonNewSearch3)
                                                .addGap(152, 152, 152)
                                                .addComponent(jLabelSelectTemp2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jRadioButtonKelvin2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jRadioButtonCelsius2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jRadioButtonFahrenheit2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelCurrentDayLayout.setVerticalGroup(
                jPanelCurrentDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCurrentDayLayout.createSequentialGroup()
                                .addGroup(jPanelCurrentDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelCurrentDayLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabelLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabelCurrentLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelCurrentDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelCurrentDayLayout.createSequentialGroup()
                                                .addComponent(jLabelSunriseTime)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanelCurrentDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabelSunset)
                                                        .addComponent(jLabelWindDirection)
                                                        .addComponent(jLabelTemperature))
                                                .addGap(7, 7, 7)
                                                .addGroup(jPanelCurrentDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanelCurrentDayLayout.createSequentialGroup()
                                                                .addGroup(jPanelCurrentDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabelCloudiness)
                                                                        .addGroup(jPanelCurrentDayLayout.createSequentialGroup()
                                                                                .addGap(3, 3, 3)
                                                                                .addComponent(jLabelPressure, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanelCurrentDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabelRain)
                                                                        .addComponent(jLabelHumidity)))
                                                        .addGroup(jPanelCurrentDayLayout.createSequentialGroup()
                                                                .addComponent(jLabelMinimumTemp)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLabelMaximumTemp))))
                                        .addGroup(jPanelCurrentDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabelStatus)
                                                .addComponent(jLabelWindSpeed)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelCurrentDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelMap, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(jPanelCurrentDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButtonNewSearch3)
                                        .addComponent(jLabelSelectTemp2)
                                        .addComponent(jRadioButtonKelvin2)
                                        .addComponent(jRadioButtonCelsius2)
                                        .addComponent(jRadioButtonFahrenheit2))
                                .addContainerGap(155, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Current Forcast", jPanelCurrentDay);

        jPanel5Day.setBackground(new java.awt.Color(51, 73, 95));
        jPanel5Day.setPreferredSize(new java.awt.Dimension(900, 360));
        jPanel5Day.setSize(new java.awt.Dimension(900, 360));

        jLabelDate1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDate1.setText("jLabel2");

        jLabelDescription1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDescription1.setText("jLabel3");

        jLabelTemp1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTemp1.setText("jLabel3");

        jLabelDescription2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDescription2.setText("jLabel3");

        jLabelTemp2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTemp2.setText("jLabel3");

        jLabelDate2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDate2.setText("jLabel2");

        jLabelDescription3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDescription3.setText("jLabel3");

        jLabelTemp3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTemp3.setText("jLabel3");

        jLabelDate3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDate3.setText("jLabel2");

        jLabelDescription4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDescription4.setText("jLabel3");

        jLabelTemp4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTemp4.setText("jLabel3");

        jLabelDate4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDate4.setText("jLabel2");

        jLabelDate5.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDate5.setText("jLabel2");

        jLabelDescription5.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDescription5.setText("jLabel3");

        jLabelTemp5.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTemp5.setText("jLabel3");

        jLabelSelectTemp1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSelectTemp1.setText("Select Temprature Unit:");

        jButtonNewSearch2.setText("Search New Location");
        jButtonNewSearch2.addActionListener(this::jButtonNewSearch2ActionPerformed);

        buttonGroup1.add(jRadioButtonKelvin1);
        jRadioButtonKelvin1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonKelvin1.setText("Kelvin");
        jRadioButtonKelvin1.addMouseListener(new java.awt.event.MouseAdapter() {

        });
        jRadioButtonKelvin1.addActionListener(this::jRadioButtonKelvin1ActionPerformed);

        buttonGroup1.add(jRadioButtonCelsius1);
        jRadioButtonCelsius1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonCelsius1.setText("Celsius");
        jRadioButtonCelsius1.addMouseListener(new java.awt.event.MouseAdapter() {

        });
        jRadioButtonCelsius1.addActionListener(this::jRadioButtonCelsius1ActionPerformed);

        buttonGroup1.add(jRadioButtonFahrenheit1);
        jRadioButtonFahrenheit1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonFahrenheit1.setText("Fahrenheit");
        jRadioButtonFahrenheit1.addActionListener(this::jRadioButtonFahrenheit1ActionPerformed);

        javax.swing.GroupLayout jPanel5DayLayout = new javax.swing.GroupLayout(jPanel5Day);
        jPanel5Day.setLayout(jPanel5DayLayout);
        jPanel5DayLayout.setHorizontalGroup(
                jPanel5DayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5DayLayout.createSequentialGroup()
                                .addGroup(jPanel5DayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5DayLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jButtonNewSearch2)
                                                .addGap(152, 152, 152)
                                                .addComponent(jLabelSelectTemp1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jRadioButtonKelvin1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jRadioButtonCelsius1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jRadioButtonFahrenheit1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel5DayLayout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addGroup(jPanel5DayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel5DayLayout.createSequentialGroup()
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel5DayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabelDate1)
                                                                        .addComponent(jLabelDescription1)
                                                                        .addComponent(jLabelTemp1)))
                                                        .addComponent(jLabelIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(78, 78, 78)
                                                .addGroup(jPanel5DayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel5DayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(jLabelDate2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jLabelDescription2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jLabelTemp2))
                                                        .addComponent(jLabelIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(67, 67, 67)
                                                .addGroup(jPanel5DayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabelDate3)
                                                        .addComponent(jLabelDescription3)
                                                        .addComponent(jLabelTemp3)
                                                        .addComponent(jLabelIcon3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(68, 68, 68)
                                                .addGroup(jPanel5DayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabelDate4)
                                                        .addComponent(jLabelDescription4)
                                                        .addComponent(jLabelTemp4)
                                                        .addComponent(jLabelIcon4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(86, 86, 86)
                                                .addGroup(jPanel5DayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabelDate5)
                                                        .addComponent(jLabelDescription5)
                                                        .addComponent(jLabelTemp5)
                                                        .addComponent(jLabelIcon5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(35, 35, 35))
        );
        jPanel5DayLayout.setVerticalGroup(
                jPanel5DayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5DayLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel5DayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5DayLayout.createSequentialGroup()
                                                .addGroup(jPanel5DayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel5DayLayout.createSequentialGroup()
                                                                .addComponent(jLabelIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(31, 31, 31))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5DayLayout.createSequentialGroup()
                                                                .addComponent(jLabelIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(31, 31, 31))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5DayLayout.createSequentialGroup()
                                                                .addComponent(jLabelIcon5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)))
                                                .addGroup(jPanel5DayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5DayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(jPanel5DayLayout.createSequentialGroup()
                                                                        .addComponent(jLabelDate1)
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(jLabelDescription1)
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(jLabelTemp1))
                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5DayLayout.createSequentialGroup()
                                                                        .addComponent(jLabelDate2)
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(jLabelDescription2)
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(jLabelTemp2)))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5DayLayout.createSequentialGroup()
                                                                .addComponent(jLabelDate5)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabelDescription5)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabelTemp5))))
                                        .addGroup(jPanel5DayLayout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(jPanel5DayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(jPanel5DayLayout.createSequentialGroup()
                                                                .addComponent(jLabelIcon4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jLabelDate4)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabelDescription4)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabelTemp4))
                                                        .addGroup(jPanel5DayLayout.createSequentialGroup()
                                                                .addComponent(jLabelIcon3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(31, 31, 31)
                                                                .addComponent(jLabelDate3)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabelDescription3)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabelTemp3)))))
                                .addGap(64, 64, 64)
                                .addGroup(jPanel5DayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButtonNewSearch2)
                                        .addComponent(jLabelSelectTemp1)
                                        .addComponent(jRadioButtonKelvin1)
                                        .addComponent(jRadioButtonCelsius1)
                                        .addComponent(jRadioButtonFahrenheit1))
                                .addContainerGap(123, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("5 Day Forcast", jPanel5Day);

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
                jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        jPanelMainLayout.setVerticalGroup(
                jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelStart.add(jPanelMain, "cardMain");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 900, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jPanelStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 360, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jPanelStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>


    //Get the city name selected from the combo box
    private void jComboBoxLocationsActionPerformed(java.awt.event.ActionEvent evt) {
        String cityName = jComboBoxLocations.getItemAt(jComboBoxLocations.getSelectedIndex());
        int spaceIndex = cityName.indexOf(",");
        if (spaceIndex != -1) {
            cityName = cityName.substring(0, spaceIndex);
        }
        WeatherInfo.getWeatherForCityName(cityName);
        card.show(jPanelStart, "cardMain");
    }

    ///////////////////////////////Clear input text boxes when clicked on \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
    private void jTextFieldLatitudeFocusGained(java.awt.event.FocusEvent evt) {
        jTextFieldLatitude.setText("");
    }

    private void jTextFieldLongitudeFocusGained(java.awt.event.FocusEvent evt) {
        jTextFieldLongitude.setText("");
    }

    private void jTextFieldSearchCityFocusGained(java.awt.event.FocusEvent evt) {
        jTextFieldSearchCity.setText("");
    }

    private void jTextFieldSearchPostCodeFocusGained(java.awt.event.FocusEvent evt) {jTextFieldSearchPostCode.setText("");}

    //////////////////////////////Add text back input text boxes \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
    private void jTextFieldSearchCityFocusLost(java.awt.event.FocusEvent evt) {jTextFieldSearchCity.setText("Search City:");}

    private void jTextFieldSearchPostCodeFocusLost(java.awt.event.FocusEvent evt) {jTextFieldSearchPostCode.setText("Search postcode:");}

    private void jTextFieldLongitudeFocusLost(java.awt.event.FocusEvent evt) {
        if (jTextFieldLongitude.getText().equals(""))
            jTextFieldLongitude.setText("Longitude: ");
    }

    private void jTextFieldLatitudeFocusLost(java.awt.event.FocusEvent evt) {
        if (jTextFieldLatitude.getText().equals(""))
            jTextFieldLatitude.setText("Latitude: ");
    }



    private void jTextFieldSearchPostCodeKeyPressed(java.awt.event.KeyEvent evt) {
        if (evt.getKeyChar() == 10) {//Check to see if user has pressed enter
            try{
                //Try to get weather for input postcode
                WeatherInfo.getWeatherForPostcode(jTextFieldSearchPostCode.getText());
                //If weather forecast found for area show main panel
                card.show(jPanelStart, "cardMain");
            }catch (Exception e){
                //Shows error a message box
                JOptionPane.showMessageDialog(this,"Please enter valid postcode","INVALID POSTCODE.",JOptionPane.WARNING_MESSAGE);
            }
        }
    }



    private void jTextFieldSearchCityKeyPressed(java.awt.event.KeyEvent evt) {
        if (evt.getKeyChar()==10){//Check to see if user has pressed enter
            try{
                //Try to get weather for input city
                WeatherInfo.getWeatherForCityName(jTextFieldSearchCity.getText());
                //If weather forecast found for area show main panel
                card.show(jPanelStart, "cardMain");
            }catch (Exception e){
                //Shows error a message box
                JOptionPane.showMessageDialog(this,"Please enter valid location","INVALID LOCATION.",JOptionPane.WARNING_MESSAGE);
            }
        }
    }


    private void searchLongLat(){
        try{
            double latVal = Double.parseDouble(jTextFieldLatitude.getText());
            double longVal = Double.parseDouble(jTextFieldLongitude.getText());
            //check to see if input coordinates are in a valid range
            if ((latVal>= -90 && latVal<=90)&&(longVal>=-180 && longVal<=180)){
                WeatherInfo.getWeatherForLongAndLat(latVal,longVal);
                //update the text boxes
                jTextFieldLatitude.setText("Latitude: ");
                jTextFieldLongitude.setText("Longitude: ");
                //If weather forecast found for area show main panel
                card.show(jPanelStart, "cardMain");

            }
            else{
                //Shows error a message box
                JOptionPane.showMessageDialog(this,"Please enter valid coordinates","INVALID COORDINATES.",JOptionPane.WARNING_MESSAGE);
            }
        }catch (Exception e ){
            //Shows error a message box
            JOptionPane.showMessageDialog(this,"Please enter valid coordinates","INVALID COORDINATES.",JOptionPane.WARNING_MESSAGE);
        }
    }


    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {
        searchLongLat();
    }

    private void jButtonCurrentLocationActionPerformed(java.awt.event.ActionEvent evt) {
        WeatherInfo.getLocation();//get users current location
        card.show(jPanelStart, "cardMain"); //If weather forecast found for area show main panel
    }

    private void jTextFieldLatitudeKeyPressed(java.awt.event.KeyEvent evt) {
        if (evt.getKeyChar()==10)//Check to see if user has pressed enter
            searchLongLat();
    }

    //////////////////////////////////////Switch panels\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
    private void jButtonNewSearch2ActionPerformed(java.awt.event.ActionEvent evt) {
        card.show(jPanelStart, "cardSearch");//
    }

    private void jButtonNewSearch3ActionPerformed(java.awt.event.ActionEvent evt) {
        card.show(jPanelStart, "cardSearch");
    }

    ///////////////////////////////Change the unit temperatures are displayed in \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
    private void jRadioButtonKelvin1ActionPerformed(java.awt.event.ActionEvent evt) {
        UpdateGUI.convertTemp(0, weather);
    }

    private void jRadioButtonCelsius1ActionPerformed(java.awt.event.ActionEvent evt) {
        UpdateGUI.convertTemp(1, weather);
    }

    private void jRadioButtonFahrenheit1ActionPerformed(java.awt.event.ActionEvent evt) {
        UpdateGUI.convertTemp(2, weather);
    }


    private void jRadioButtonFahrenheit2ActionPerformed(java.awt.event.ActionEvent evt) {
        for (JSONWeatherParser.weather weather1 : weatherForecast) {
            UpdateGUI.convertTemp(2,weather1);
        }
    }


    private void jRadioButtonCelsius2ActionPerformed(java.awt.event.ActionEvent evt) {
        for (JSONWeatherParser.weather weather1 : weatherForecast) {
            UpdateGUI.convertTemp(1,weather1);
        }
    }

    private void jRadioButtonKelvin2ActionPerformed(java.awt.event.ActionEvent evt) {
        for (JSONWeatherParser.weather weather1 : weatherForecast) {
            UpdateGUI.convertTemp(0,weather1);
        }
    }






    // Variables declaration - do not modify
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonCurrentLocation;
    private javax.swing.JButton jButtonNewSearch2;
    private javax.swing.JButton jButtonNewSearch3;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JComboBox<String> jComboBoxLocations;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabelCloudiness;
    private javax.swing.JLabel jLabelCurrentLocation;
    private javax.swing.JLabel jLabelDate1;
    private javax.swing.JLabel jLabelDate2;
    private javax.swing.JLabel jLabelDate3;
    private javax.swing.JLabel jLabelDate4;
    private javax.swing.JLabel jLabelDate5;
    private javax.swing.JLabel jLabelDescription1;
    private javax.swing.JLabel jLabelDescription2;
    private javax.swing.JLabel jLabelDescription3;
    private javax.swing.JLabel jLabelDescription4;
    private javax.swing.JLabel jLabelDescription5;
    private javax.swing.JLabel jLabelHumidity;
    private javax.swing.JLabel jLabelIcon;
    private javax.swing.JLabel jLabelIcon1;
    private javax.swing.JLabel jLabelIcon2;
    private javax.swing.JLabel jLabelIcon3;
    private javax.swing.JLabel jLabelIcon4;
    private javax.swing.JLabel jLabelIcon5;
    private javax.swing.JLabel jLabelLocation;
    private javax.swing.JLabel jLabelMap;
    private javax.swing.JLabel jLabelMaximumTemp;
    private javax.swing.JLabel jLabelMinimumTemp;
    private javax.swing.JLabel jLabelPressure;
    private javax.swing.JLabel jLabelRain;
    private javax.swing.JLabel jLabelSelectCity;
    private javax.swing.JLabel jLabelSelectTemp1;
    private javax.swing.JLabel jLabelSelectTemp2;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelSunriseTime;
    private javax.swing.JLabel jLabelSunset;
    private javax.swing.JLabel jLabelTemp1;
    private javax.swing.JLabel jLabelTemp2;
    private javax.swing.JLabel jLabelTemp3;
    private javax.swing.JLabel jLabelTemp4;
    private javax.swing.JLabel jLabelTemp5;
    private javax.swing.JLabel jLabelTemperature;
    private javax.swing.JLabel jLabelWindDirection;
    private javax.swing.JLabel jLabelWindSpeed;
    private javax.swing.JPanel jPanel5Day;
    private javax.swing.JPanel jPanelCurrentDay;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelSearch;
    private javax.swing.JPanel jPanelStart;
    private javax.swing.JRadioButton jRadioButtonCelsius1;
    private javax.swing.JRadioButton jRadioButtonCelsius2;
    private javax.swing.JRadioButton jRadioButtonFahrenheit1;
    private javax.swing.JRadioButton jRadioButtonFahrenheit2;
    private javax.swing.JRadioButton jRadioButtonKelvin1;
    private javax.swing.JRadioButton jRadioButtonKelvin2;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTextField jTextFieldLatitude;
    private javax.swing.JTextField jTextFieldLongitude;
    private javax.swing.JTextField jTextFieldSearchCity;
    private javax.swing.JTextField jTextFieldSearchPostCode;
    // End of variables declaration
}
